version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postegres
    environment:
      POSTGRES_DB: product_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"


