server:
  port: 8080

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/product_management
    username: admin
    password: admin
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: admin
      timeout: 20000

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
    file: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'

