server:
  port: 8080
spring:
  main:
    banner-mode: off
logging:
  level:
    root: INFO
  pattern:
    console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
    file: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'