version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    image: postgres:latest
    container_name: postegres
    environment:
      POSTGRES_DB: product_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - /postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d product_management -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  internal:
    driver: bridge