# This is a basic workflow to help you get started with Actions

#name: Build-Publish
#
#on:
##  push:
##    branches: [ "main" ]
#
#  workflow_dispatch:
#jobs:
#  Build:
#    environment: Prod
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Download repository
#        uses: actions/checkout@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: yanzingra/product-management:latest,yanzingra/product-management:${{ github.run_number }}