# This is a basic workflow to help you get started with Actions

name: workflow-practice

on:
  push:
#    branches: [ "main" ]
    tags:
      - '*'

  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: test tag increase
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "Tag name from github.ref_name: $TAG"