# This is a basic workflow to help you get started with Actions

name: Deploy-Azure

on:
  push:
    branches: [ "main" ]
#  workflow_run:
#    workflows:
#      - Build-Publish
#    types:
#      - completed
jobs:
  Build:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURECLIENTSECRET }}
          tenant-id: ${{ secrets.AZURETENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
