# This is a basic workflow to help you get started with Actions

name: workflow-practice

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  Build:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yanzingra/product-management

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}