# This is a basic workflow to help you get started with Actions

name: workflow-practice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: gradle

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.10.0
  Upload_artifact:
    name: Push Docker image to Docker Hub
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest